services:
  - type: web
    name: statsforecast-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
